### ISSUE TITLE
pyusb / libusb not detecting device

### ISSUE THREAD

**Issue by userlandkernel** [checkra1n/PongoKit#1]
I've tried both brew and from source compilation of libusb.
I also tried reinstalling pyusb and using another python version.
However, it can still not detect my device.

In my own mvusblib it works and detects the device as PongoOS USB device, just like System Information app does.
However, making the control requests via my own USB library for sending a command leads to the device panicking.

The device used was an iPhone 6S, connected to a MacOS computer on El Capitan.
Please help me get my device detected so I can start developing pongoOS modules.

**Comment by woachk** [comment]
Hello, 

This is not an issue with the pongoOS SDK. The pongoOS USB stack is currently broken on Apple A9-based devices.

**Comment by woachk** [comment]
Fixed on s8000, however the A7 and A8 issues remain.
