### ISSUE TITLE
Where do i get the cross compiler?

### ISSUE THREAD

**Issue by Witherking25** [checkra1n/PongoKit#3]

**Comment by PhildoDxldo** [comment]
Here’s one. 

https://github.com/maxint/arcbuild

**Comment by Witherking25** [comment]
I meant for PongoKit. I am on Linux

**Comment by Witherking25** [comment]
I’m trying to compile the example

**Comment by Witherking25** [comment]
Would this work?
https://github.com/tpoechtrager/cctools-port/tree/master/usage_examples/ios_toolchain

**Comment by Witherking25** [comment]
the one i linked works
